### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by elgarty** [FuelRats/FCMS#173]
On the step _Load default data into database_ it errors with this:
`Traceback (most recent call last):
  File "/home/mmuchi030674/FCMS-master/env/bin/initialize_FCMS_db", line 8, in <module>
    sys.exit(main())
  File "/home/mmuchi030674/FCMS-master/FCMS/scripts/initialize_db.py", line 36, in main
    setup_models(dbsession)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_manager.py", line 142, in __exit__
    self.commit()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_manager.py", line 133, in commit
    return self.get().commit()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_transaction.py", line 282, in commit
    raise v.with_traceback(tb)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_transaction.py", line 273, in commit
    self._commitResources()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_transaction.py", line 456, in _commitResources
    raise v.with_traceback(tb)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/transaction/_transaction.py", line 428, in _commitResources
    rm.tpc_begin(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/zope/sqlalchemy/datamanager.py", line 140, in tpc_begin
    self.session.flush()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    for (
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 221, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1726, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "<string>", line 2, in connection
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 995, in connection
    return self._connection_for_bind(bind, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1129, in _connection_for_bind
    conn = self._parent._connection_for_bind(
  File "<string>", line 2, in _connection_for_bind
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
    return self._connection_cls(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
    return self.pool.connect()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 170, in _do_get
    self._dec_overflow()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/mmuchi030674/FCMS-master/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
TypeError: 'options' is an invalid keyword argument for this function`

is this fixable?

**Comment by kenneaal** [comment]
FCMS does not need DB initialization, this is boilerplate from the Pyramid pylons. Once alembic has run, you can start the server.
This is also an upstream error from SQLAlchemy, not from FCMS itself.
